/ifm3d_ros2/camera0:
  ros__parameters:
    pcic_port: 50010

/ifm3d_ros2/camera1:
  ros__parameters:
    pcic_port: 50011

/ifm3d_ros2/camera2:
  ros__parameters:
    pcic_port: 50012
    
/ifm3d_ros2/camera3:
  ros__parameters:
    pcic_port: 50013

/ifm3d_ros2/camera4:
  ros__parameters:
    pcic_port: 50014

/ifm3d_ros2/camera5:
  ros__parameters:
    pcic_port: 50015        